Name:           ros-indigo-icart-mini
Version:        0.1.3
Release:        1%{?dist}
Summary:        ROS icart_mini package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/icart_mini
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-combine-dr-measurements
Requires:       ros-indigo-force-rotate-recovery
Requires:       ros-indigo-icart-mini-control
Requires:       ros-indigo-icart-mini-description
Requires:       ros-indigo-icart-mini-driver
Requires:       ros-indigo-icart-mini-gazebo
Requires:       ros-indigo-icart-mini-navigation
Requires:       ros-indigo-waypoints-navigation
BuildRequires:  ros-indigo-catkin

%description
This package provides packages related to navigation of i-Cart mini.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Sep 14 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.1.3-1
- Autogenerated by Bloom

* Wed Apr 29 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.1.3-0
- Autogenerated by Bloom

* Tue Apr 28 2015 Daiki Maekawa <method_aspect_card@yahoo.co.jp> - 0.1.2-1
- Autogenerated by Bloom

* Mon Dec 29 2014 Daiki Maekawa <method_aspect_card@yahoo.co.jp> - 0.1.2-0
- Autogenerated by Bloom

* Wed Dec 17 2014 Daiki Maekawa <method_aspect_card@yahoo.co.jp> - 0.1.1-2
- Autogenerated by Bloom

* Wed Dec 17 2014 Daiki Maekawa <method_aspect_card@yahoo.co.jp> - 0.1.1-1
- Autogenerated by Bloom

* Wed Dec 17 2014 Daiki Maekawa <method_aspect_card@yahoo.co.jp> - 0.1.1-0
- Autogenerated by Bloom

* Tue Dec 09 2014 Daiki Maekawa <method_aspect_card@yahoo.co.jp> - 0.0.5-0
- Autogenerated by Bloom

* Tue Dec 02 2014 Daiki Maekawa <method_aspect_card@yahoo.co.jp> - 0.0.3-1
- Autogenerated by Bloom

* Tue Dec 02 2014 Daiki Maekawa <method_aspect_card@yahoo.co.jp> - 0.0.3-0
- Autogenerated by Bloom

